variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker

# Official docker compose image.
image:
  name: docker/compose:latest

services:
  - name: docker:dind
    command: ["--privileged"]  # Enable privileged mode for DinD

before_script:
  - docker version
  - docker-compose version

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec flask-app pytest app/tests
    - docker-compose down
