image: docker
services:
  - docker:dind

stages:
  - lint
  - build
  - unit_tests
  - integration_tests

# Linting stage (Check for proper formatting and checkstyle rules)
lint:
  stage: lint
  script:
    - docker-compose run --rm voting_app black --check .
    - docker-compose run --rm voting_app flake8 .
    - docker-compose run --rm authentication_service black --check .
    - docker-compose run --rm authentication_service flake8 .

build:
  stage: build
  script:
    - docker-compose build

unit_tests:
  stage: unit_tests
  script:
    - docker-compose run --rm voting_app python -m unittest discover -s voting_app/tests/unit
    - docker-compose run --rm authentication_service python -m unittest discover -s authentication_service/tests/unit

integration_tests:
  stage: integration_tests
  script:
    - docker-compose up -d
    - docker-compose exec voting_app pytest voting_app/tests/integration
    - docker-compose down
