image: alpine

services:
  - docker:19.03.12-dind

before_script:
  - apk update && apk add docker-compose

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec flask-app pytest app/tests
    - docker-compose down
