image: docker
services:
  - docker:dind

stages:
  - lint
  - build
  - unit_tests
  - integration_tests
# Linting stage (Check for proper formatting and checktyle rules)

lint:
  stage: lint
  allow_failure: true
  script:
    - docker-compose run --rm voting_app black --check .
    - docker-compose run --rm voting_app flake8 .
    - docker-compose run --rm authentication_app black --check .
    - docker-compose run --rm authentication_app flake8 .

build:
  stage: build
  script:
    - docker-compose build

unit_tests:
  stage: unit_tests
  script:
    - docker-compose run --rm voting_app python -m unittest discover -s application/tests/unit
# Add after adding unit tests for authentication
#    - docker-compose run --rm authentication_app python -m unittest discover -s application/tests/unit
# discover command: This is a unittest sub-command that automatically discovers and runs tests in
# the specified directory. It looks for test files matching the pattern test*.py by default.

integration_tests:
  stage: integration_tests
  script:
    - docker-compose up -d
    - docker-compose exec voting_app python -m pytest application/tests/integration
    - docker-compose exec authentication_app python -m -s pytest application/tests/integration
    - docker-compose down