image: docker
services:
  - docker:dind

stages:
  - lint
  - build
  - unit_tests
  - integration_tests
  -
# Linting stage (Check for proper formatting and checktyle rules)

lint:
  stage: lint
  script:
    - docker-compose run --rm flask-app black --check .
    - docker-compose run --rm flask-app flake8 .

build:
  stage: build
  script:
    - docker-compose build

unit_tests:
  stage: unit_tests
  script:
    - docker-compose run --rm flask-app python -m unittest discover -s app/tests/unit
# discover command: This is a unittest sub-command that automatically discovers and runs tests in
# the specified directory. It looks for test files matching the pattern test*.py by default.

integration_tests:
  stage: integration_tests
  script:
    - docker-compose up -d
    - docker-compose exec flask-app pytest app/tests/integration
    - docker-compose down