version: '3'
services:
  voting_app:
    build: ./voting_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  authentication_service:
    build: ./authentication_service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  