version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  flask-app:
    build: .
    command: flask run --host=0.0.0.0 --cert=cert.pem --key=key-no-pass.pem
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
