version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  voting_app:
    build: ./app/voting_app
    container_name: voting_app
    command: python -m application.app
    volumes:
      - ./app/voting_app:/usr/src/app
      - ./certs:/certs
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  voting_app_2:
    build: ./app/voting_app_2
    container_name: voting_app_2
    command: python -m application.app
    volumes:
      - ./app/voting_app_2:/usr/src/app
      - ./certs:/certs
    ports:
      - "5001:5001"
    depends_on:
      - mongo

## Define the volume at the bottom
#volumes:
#  mongo_data: