version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Add this line to persist data
  flask-app:
    build: .
    command: python app.py
    volumes:
      - .:/usr/src/app
      - ./certs:/certs
    ports:
      - "5000:5000"
    depends_on:
      - mongo

# Define the volume at the bottom
volumes:
  mongo_data: